parameters:
  vmImage: ''

stages:
- stage: Build_Test_Solution
  jobs:
  - job:
    displayName: "Build & Test Solution"
  
    pool:
      vmImage: ${{ parameters.vmImage }}
    
    steps:
      - template: ../steps/solution-management/solution-build-recommended.yml
