parameters:
  name: 'Build_Test_Solution'
  vmImage: ''

stages:
- stage: ${{ parameters.name }}
  jobs:
  - job:
    displayName: "Build & Test Solution"
  
    pool:
      vmImage: ${{ parameters.vmImage }}
    
    steps:
      - template: ../steps/solution-management/solution-build-recommended.yml
