stages:
- stage: Build_Test_CSharp
  jobs:
  - job:
    displayName: "Build & Test .NET Code"
  
    pool:
      vmImage: 'vs2017-win2016'
    steps:

      - template: ../steps/build-dotNet-source.yml

      - task: VSTest@2
        displayName: 'VsTest - Test assemblies'
        inputs:
          testAssemblyVer2: |
            **\*test*.dll
            !**\*TestAdapter.dll
            !**\obj\**
            !**\UI\**