stages:
- stage: Build_Test_CSharp
  jobs:
  - job:
    displayName: "Build & Test .NET Code"
  
    pool:
      vmImage: 'vs2017-win2016'
    steps:

      - template: ../steps/build-dotNet-source.yml
      - template: ../steps/test-dotNet-source.yml

