stages:
- stage: Build_Test_CSharp
  jobs:
  - job:
    displayName: "Build & Test .NET Code"
  
    pool:
      vmImage: 'vs2017-win2016'
    steps:

      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 4.3.0'

      - task: NuGetCommand@2
        displayName: 'NuGet restore'

      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
        displayName: "Build .NET Solution"

      - task: VSTest@2
        displayName: 'VsTest - Test assemblies'
        inputs:
          testAssemblyVer2: |
            **\*test*.dll
            !**\*TestAdapter.dll
            !**\obj\**
            !**\UI\**