stages:
- stage: Build_Test_CSharp
  jobs:
  - job:
    displayName: "Build & Test .NET Code"
  
    pool:
      vmImage: 'vs2017-win2016'
    
    steps:
      - template: ../steps/dotNet/build-dotNet-source.yml
      - template: ../steps/dotNet/test-dotNet-source.yml

